### ISSUE TITLE
Investigate feasibility of building a tool to extract the wallet addresses from the wallet DB.

### ISSUE THREAD

**Issue by aaroncarpenter** [aaroncarpenter/fork-board#34]
Extract the puzzle hashes 
convert to bech32m with xch prefix to get wallet addresses

**Comment by centrd** [comment]
This would be awesome. I've been using ForkFarmer to get an overview of balances until now, and one issue it has is it makes updates of Chia and forks fail. I believe this happens because it polls the info by calling the executable for each fork. I imagine fork-board might have a similar effect. If the necessary info can be read from the DB file directly, then updates can be run without having to close the application.

**Comment by aaroncarpenter** [comment]
Hi. The existing ForkBoard app doesn't hit the fork dbs at all, completely decoupled. It retrieves all of its balance information from the alltheblocks apis based on the wallets you enter.  No need to access the wallet dbs. 

I am working on a separate tool to extract wallet addresses from the fork dbs. It does require access to the fork dbs, but it just connects very briefly to retrieve the data points it needs then closes the connection so it shouldn't lock any of the fork apps out of the db.

**Comment by aaroncarpenter** [comment]
Closing....  Currently testing Wallet Tool in pre-release.
