### ISSUE TITLE
1.0.5 is Apple Silicon only!

### ISSUE THREAD

**Issue by bobba84** [aaroncarpenter/fork-board#50]
What happened to the Intel compatibility?

**Comment by aaroncarpenter** [comment]
My apologies about that.  I did build this version on my new macbook so that would make sense.  Didn't think about the incompatibility there.  let me see what I can do to get a version built on a intel compatible system.

**Comment by aaroncarpenter** [comment]
@bobba84, My Intel-based Mac Build VM has been causing trouble and not wanting to start up.  I had a colleague build it for me on an Intel Mac.  You can find the DMG file here.  https://drive.google.com/file/d/1s4om0AfrM_6wB_-BQjsEK_AIMbNFL2Xm/view?usp=sharing.  I can't add it into the repository because I think having two DMG files present would break the version checker functionality for now.  I will work on a fix for this.

**Comment by bobba84** [comment]
Thank you very much!
